apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon
  template:
    metadata:
      labels:
        app: coupon
    spec:
      containers:
        - name: coupon
          image: insonia78/services/coupon
          env:
            # - name: NATS_CLIENT_ID
            #   valueFrom:
            #        fieldRef:
            #            fieldPath: metadata.name 
            # - name: NATS_URL
            #   value: 'http://nats-srv:4222' 
            # - name: NATS_CLUSTER_ID
            #   value: prescriptions
                       
            # - name: ZIP_LOOKUP_ADDRESS
            #   value: http://ZiptasticAPI.com/
            - name: MED_IMPACT_URL
              value: https://https://rxsavings-ws.medimpact.com/cashcard-ws-v1_0/soap/cashcard 
            
---
apiVersion: v1
kind: Service
metadata:
  name: coupon-srv
spec:
  selector:
    app: coupon
  ports:
    - name: coupon
      protocol: TCP
      port: 6000
      targetPort: 6000