apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: ingress-srv
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: location.com
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: location-srv
              servicePort: 5000
             
