apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: ingress-srv
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: firstrx.dev
      http:
        paths:
          - path: /text-message/graphql
            backend:
              serviceName: text-messages-srv
              servicePort: 7000
          - path: /coupon/graphql
            backend:
              serviceName: coupon-srv
              servicePort: 6000  
          - path: /location/graphql
            backend:
              serviceName: location-srv
              servicePort: 5000
          - path: /prescriptions/graphql
            backend:
              serviceName: prescriptions-srv
              servicePort: 4000          
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
         
             
