apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: ingress-srv
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: firstrx.dex
      http:
        paths:
          - path: location/graphql
            backend:
              serviceName: location-srv
              servicePort: 5000
          - path: 
            backend:
              serviceName: client-srv
              servicePort: 3000
          - path: text-message/graphql
            backend:
              serviceName: text-messages-srv
              servicePort: 7000
         
             
