apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: ingress-srv
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: location.com
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: location-srv
              servicePort: 5000
    - host: client.com
      http:
        paths:
          - path: 
            backend:
              serviceName: client-srv
              servicePort: 3000
    - host: text-messages.com
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: text-messages-srv
              servicePort: 7000
         
             
